# Generated by Django 5.1 on 2024-08-25 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view", "Can view items"),
                    ("can_create", "Can create items"),
                    ("can_edit", "Can edit items"),
                    ("can_delete", "Can delete items"),
                ]
            },
        ),
    ]
